packages:
  - packages/*

allowBuilds:
  '@prisma/engines': set this to true or false
  better-sqlite3: set this to true or false
  esbuild: true
  lightningcss: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false
